## @section Ingress parameters
##
ingress:
  ## @param ingress.enabled Enable or disable the ingress
  ##
  enabled: true
  ## @param ingress.className The class name for the ingress
  ##
  className: nginx
  ## @param ingress.clusterIssuerRef The cluster issuer reference for the ingress
  ##
  clusterIssuerRef:
  ## @param ingress.host The host for the ingress
  ##
  host: odoo.knd.local
  ## @param ingress.customDomain The custom domain for the ingress
  ##
  customDomain: ""

## @section vshnPostgres parameters
##
vshnPostgres:
  ## @param vshnPostgres.enabled Enable or disable vshnPostgres
  ##
  enabled: false
  ## @param vshnPostgres.secretRef The secret reference for vshnPostgres
  ##
  secretRef: odoo-postgresql
  client:
    ## @param vshnPostgres.client.enabled Enable or disable the vshnPostgres client
    ##
    enabled: false

## @section Postgres parameters
##
postgres:
  ## @param postgres.enabled Enable or disable Postgres
  ##
  enabled: false
  ## @param postgres.db The database name for Postgres
  ##
  db: odoo
  ## @param postgres.user The username for Postgres
  ##
  user: odoo
  ## @param postgres.secretRef The secret reference for Postgres
  ##
  secretRef: odoo-postgres
  ## @param postgres.userPasswordKey The user password key for Postgres
  ##
  userPasswordKey: password
  ## @param postgres.storageClassName Set the storage class
  ##
  storageClassName: standard

## @section PostgreSQL parameters
##
postgresql:
  ## @param postgresql.enabled Enable or disable PostgreSQL
  ##
  enabled: false
  auth:
    ## @param postgresql.auth.username The username for PostgreSQL authentication
    ##
    username: odoo
    ## @param postgresql.auth.database The database name for PostgreSQL authentication
    ##
    database: odoo
    ## @param postgresql.auth.existingSecret Name of the secret key.
    ##
    existingSecret: odoo-postgresql
    secretKeys:
      ## @param postgresql.auth.secretKeys.adminPasswordKey The admin password key for PostgreSQL
      ##
      adminPasswordKey: "postgres-password"
      ## @param postgresql.auth.secretKeys.userPasswordKey The user password key for PostgreSQL
      ##
      userPasswordKey: "password"

## @section CloudNativePG parameters
##
cnpg:
  enabled: true
  cluster:
    ## @param cnpg.cluster.nameOverride Override the name of the PostgreSQL cluster
    ## Default: "{release-name}-postgresql"
    ##
    nameOverride: ""
    ## @param cnpg.cluster.instances Number of PostgreSQL instances (1 for single, 2+ for high availability)
    ##
    instances: 1
    storage:
      ## @param cnpg.cluster.storage.size Persistent volume size for each instance
      ##
      size: 4Gi
    ## @param cnpg.bootstrap Configure a database to run on cluster creation
    bootstrap:
      initdb:
        ## @param cnpg.database.name Name of the PostgreSQL database to create
        ##
        name: odoo
        ## @param cnpg.database.user Name of the database user (optional, defaults to database name)
        ##
        user: odoo
        hostname: odoo-db
        majorVersion: 16
        ## @param cnpg.database.secretName Name of the secret to store credentials
        ## Default: {release-name}-cnpg-credentials
        ##
        secretName: "odoo-postgresql"

## @section Odoo parameters
##
## @param enabled Enable or disable Odoo
##
enabled: true
## @param image The image for odoo
##
image: mintsystem/odoo:18.0.20250725
## @param imagePullPolicy Pull policy for Odoo image
##
imagePullPolicy: Always
## @param proxyMode Enable or disable proxy mode for Odoo
##
proxyMode: true
## @param downloadOdooEnterprise Enable or disable downloading Odoo Enterprise
##
downloadOdooEnterprise: false
## @param addonsGitRepos List of addon Git repositories for Odoo
##
addonsGitRepos:
  - https://github.com/Mint-System/Odoo-Apps-Server-Tools.git#18.0
  - https://github.com/OCA/Server-Tools.git#18.0
  - https://github.com/OCA/Project.git#18.0
## @param database The database for odoo
##
database: odoo
## @param initLang The initial language for Odoo
##
initLang: de_CH
## @param listDB Enable or disable listing databases for Odoo
##
listDB: false
## @param githubAddonsCredentialsSecretName Name of secret containing GITHUB_USERNAME and GITHUB_PERSONAL_ACCESS_TOKEN with access to the addons repo.
##
githubAddonsCredentialsSecretName: odoo-github
## @section K8up parameters
##
k8up:
  ## @param k8up.enabled Enable or disable K8up
  ##
  enabled: false
